### ISSUE TITLE
Invalid JSON parsing

### ISSUE THREAD

**Issue by smontgomerie** [hookbox/hookbox#2]
Passing in this URL fails with ExpectedException: Invalid json for payload:
    /web/publish?payload=%7B%22code%22:%22new_task%22,%22message%22:%22Task%20was%20successfully%20created.%22,%22status_id%22:1,%22project_id%22:13,%22test%22:%22complete:function(request)%7B$('.dashboard_task[task_id=205]%20.dashboard_task_loading').hide();%7D%22,%22release_id%22:-1,%22result%22:true%7D&channel_name=testing&security_token=secret

The payload should be decoded as this, which is valid JSON:
    {"code":"new_task","message":"Task was successfully   created.","status_id":1,"project_id":13,"test":"complete:function(request){$('.dashboard_task[task_id=205] .dashboard_task_loading').hide();}","release_id":-1,"result":true}

I suspect it has something to do with having curly braces in its content.

**Comment by smontgomerie** [comment]
I have determined that it's the semicolon that's screwing it up. Replacing ";" in the url with %3B fixes the problem.

**Comment by ergo** [comment]
json encoding/decifing is carried out by pythons json lib/ simplejson on 2.5 - are you sure its not an issue with badly encoded data you try to pass ?
